name: 🐞 Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for using Orca Slicer and wanting to report a bug.**
        
        Please note that this is not the place to make feature requests or ask for help.
        For this, please use the [Feature request](https://github.com/SoftFever/OrcaSlicer/issues/new?assignees=&labels=&projects=&template=feature_request.yml) issue type or you can discuss your idea on our [Discord server](https://discord.gg/P4VE9UY9gJ) with others.
        
        Before filing, please check if the issue already exists (either open or closed) by using the search bar on the issues page. If it does, comment there. Even if it's closed, we can reopen it based on your comment.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this problem?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: os_type
    attributes:
      label: "Operating System (OS)"
      description: "What OSes are you are experiencing issues on?"
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Screenshots? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
